### PR TITLE
update pkgdown github action

### LINKED ISSUE #2: Fix pkgdown github action
Breaking with git login issues. Need to update all our R packages.

See some of the recent changes in this file https://github.com/r-lib/usethis/blob/master/.github/workflows/pkgdown.yaml

### PR DESCRIPTION
**Pull request by chacalle**
Reran `usethis::use_github_action(name = "pkgdown")`. I can do this in the other packages as well if this works

### CODE REVIEW

**Comment by chacalle** [comment]
I wish there was a better way to propagate this to the other packages

**Comment by krpaulson** [comment]
Is `usethis::use_github_action(name = "pkgdown")` documented in "how this template was created" in the wiki?

**Review by krpaulson — APPROVED** [review]
Looks fine to me if this works

**Comment by chacalle** [comment]
> Is `usethis::use_github_action(name = "pkgdown")` documented in "how this template was created" in the wiki?

Yup!

**Pull request merged**
